name = "ElementaryFluxModes"
uuid = "89210afb-bb0f-413a-8ffa-8390a41acbf2"
authors = ["HettieC <hester.chapman@btinternet.com> and contributors"]
version = "0.2.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FastDifferentiation = "eb9bf01b-bf85-4b60-bf87-ee5de06c00be"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RowEchelon = "af85af4c-bcd5-5d23-b03a-a909639aa875"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
AbstractFBCModels = "1"
DocStringExtensions = "0.9"
FastDifferentiation = "0.4.3"
JuMP = "1.23.6"
RowEchelon = "0.2"
SparseArrays = "1"
Test = "1.11.0"
julia = "1"

[extras]
AbstractFBCModels = "5a4f3dfa-1789-40f8-8221-69268c29937c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AbstractFBCModels", "Test"]
