name = "ElementaryFluxModes"
uuid = "89210afb-bb0f-413a-8ffa-8390a41acbf2"
authors = ["HettieC <hester.chapman@btinternet.com> and contributors"]
version = "1.0.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FastDifferentiation = "eb9bf01b-bf85-4b60-bf87-ee5de06c00be"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RowEchelon = "af85af4c-bcd5-5d23-b03a-a909639aa875"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
AbstractFBCModels = "1"
DocStringExtensions = "0.9"
FastDifferentiation = "0.4"
JuMP = "1"
RowEchelon = "0.2"
SparseArrays = "1"
julia = "1"

[extras]
AbstractFBCModels = "5a4f3dfa-1789-40f8-8221-69268c29937c"
COBREXA = "babc4406-5200-4a30-9033-bf5ae714c842"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ConstraintTrees = "5515826b-29c3-47a5-8849-8513ac836620"
DifferentiableMetabolism = "9677e053-0fc1-49e6-98a8-2ad3a1525e54"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSONFBCModels = "475c1105-d6ed-49c1-9b32-c11adca6d3e8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tulip = "6dd1b50a-3aae-11e9-10b5-ef983d2400fa"

[targets]
test = ["Test", "AbstractFBCModels", "COBREXA", "CairoMakie", "ConstraintTrees", "DifferentiableMetabolism", "JSON", "JSONFBCModels", "Tulip", "DataFrames"]
