name = "ElementaryModes"
uuid = "89210afb-bb0f-413a-8ffa-8390a41acbf2"
authors = ["HettieC <hester.chapman@btinternet.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
