name = "ElementaryFluxModes"
uuid = "89210afb-bb0f-413a-8ffa-8390a41acbf2"
authors = ["HettieC <hester.chapman@btinternet.com> and contributors"]
version = "0.1.0"

[deps]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RowEchelon = "af85af4c-bcd5-5d23-b03a-a909639aa875"

[compat]
AbstractFBCModels = "1.2.0"
Coverage = "1.6.1"
julia = "1.9"
DocStringExtensions = "0.9.3"
RowEchelon = "0.2.1"

[extras]
AbstractFBCModels = "5a4f3dfa-1789-40f8-8221-69268c29937c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AbstractFBCModels", "Test"]
