name = "ElementaryFluxModes"
uuid = "89210afb-bb0f-413a-8ffa-8390a41acbf2"
authors = ["HettieC <hester.chapman@btinternet.com> and contributors"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
RowEchelon = "af85af4c-bcd5-5d23-b03a-a909639aa875"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TerminalPager = "0c614874-6106-40ed-a7c2-2f1cd0bff883"

[compat]
AbstractFBCModels = "1"
DocStringExtensions = "0.9"
JuliaFormatter = "1.0.62"
OhMyREPL = "0.5.28"
RowEchelon = "0.2"
SparseArrays = "1"
TerminalPager = "0.6.0"
julia = "1"

[extras]
AbstractFBCModels = "5a4f3dfa-1789-40f8-8221-69268c29937c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AbstractFBCModels", "Test"]
